### ISSUE TITLE
Typing should focus on searchbar

### ISSUE THREAD

**Issue by anagstef** [anagstef/ion-cheat-sheet#2]
**Is your feature request related to a problem? Please describe.**
When the user clicks outside the searchbar, they have to focus on the searchbar again to start typing.

**Describe the solution you'd like**
Typing letters even if the searchbar is not focused. It should focus on it.

**Comment by NickolasBenakis** [comment]
I take this one

**Comment by anagstef** [comment]
@NickolasBenakis Thanks for the PR!
